# List of dependencies of the project

[versions]
arrow = "2.2.3"                       # https://github.com/arrow-kt/arrow/releases

lincheck = "3.7"                      # https://github.com/JetBrains/lincheck/releases

kotlinx-coroutines = "1.11.0"         # https://github.com/Kotlin/kotlinx.coroutines/releases

kotlin-js = "2026.7.7"                # https://central.sonatype.com/artifact/org.jetbrains.kotlin-wrappers/kotlin-js

[plugins]

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinJs = { module = "org.jetbrains.kotlin-wrappers:kotlin-js", version.ref = "kotlin-js" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
lincheck = { module = "org.jetbrains.lincheck:lincheck", version.ref = "lincheck" }
