# List of dependencies of the project

[versions]
arrow = "2.2.3"                       # https://github.com/arrow-kt/arrow/releases
lincheck = "2.39"                     # https://github.com/JetBrains/lincheck/releases
kotlinx-coroutines = "1.10.2"         # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlin-js = "2025.7.6"                # https://central.sonatype.com/artifact/org.jetbrains.kotlin-wrappers/kotlin-js

[plugins]

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinJs = { module = "org.jetbrains.kotlin-wrappers:kotlin-js", version.ref = "kotlin-js" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
lincheck = { module = "org.jetbrains.kotlinx:lincheck", version.ref = "lincheck" }
